# baseURL is handeled via env var with -b flag 
# (https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site/#deploy-with-cloudflare-pages)
languageCode = "en-us"
title = "expstew"
theme = "smol"
