# baseURL is handeled via env var with -b flag 
# (https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site/#deploy-with-cloudflare-pages)
enableEmoji = true
title = "expstew"
theme = "smol"

defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true
# [menu.main]
# url = "https://github.com/expstew"
# title = "Source Code"

[languages]
  [languages.en]
    disabled = false
    languageCode = "en"
    languageDirection = "ltr"
    languageName = "English"
    weight = 1
    [languages.en.params]
      subtitle = "Cornflowers are blue."
    [languages.en.menu]
      [[languages.en.menu.footer]]
        name = "Source Code"
        url = "https://github.com/expstew/website"
        weight = 1 


  [languages.de]
    disabled = false
    languageCode = "de-DE"
    languageDirection = "ltr"
    languageName = "Deutsch"
    weight = 2
    [languages.de.params]
      subtitle = "Kornblumen sind blau."
    [languages.de.menu]
      [[languages.de.menu.footer]]
        name = "Quellcode"
        url = "https://github.com/expstew/website"
        weight = 1 


